databaseChangeLog:
  - include:
      file: changelog/auth-001_initial_schema.sql
      relativeToChangelogFile: true
  - include:
      file: changelog/auth-002_add_user_data.sql
      relativeToChangelogFile: true
