databaseChangeLog:
  - include:
      file: module/authentication/changelog.yaml
      relativeToChangelogFile: true
  - include:
      file: module/product/changelog.yaml
      relativeToChangelogFile: true