databaseChangeLog:
  - include:
      file: changelog/product-001_initial_product_schema.sql
      relativeToChangelogFile: true
  - include:
      file: changelog/product-002_create_product.sql
      relativeToChangelogFile: true
