spring.application.name=spring-boot-liquibase

spring.config.import=file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/liquibasedb}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
